table Table1
	lineageTag: ef9cca88-56b4-4641-8f9f-6735e0364fd0

	column @name
		dataType: string
		lineageTag: 66939985-f4ef-4f2f-a0ab-d3231743ede0
		summarizeBy: none
		sourceColumn: @name

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: fd190252-c2b2-44b9-88e4-a274b3846e74
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	partition Table1 = m
		mode: import
		source =
				let
				    ソース = Excel.Workbook(Web.Contents("https://mngenvmcap140481.sharepoint.com/sites/true/Shared%20Documents/%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB.xlsx"), null, true),
				    Table1_Table = ソース{[Item="Table1",Kind="Table"]}[Data],
				    変更された型 = Table.TransformColumnTypes(Table1_Table,{{"name", type text}, {"ID", Int64.Type}}),
				    #"名前が変更された列 " = Table.RenameColumns(変更された型,{{"name", "@name"}})
				in
				    #"名前が変更された列 "

	annotation PBI_NavigationStepName = ナビゲーション

	annotation PBI_ResultType = Table

