table 【並び替え用】運用区分
	lineageTag: 5d7a0b82-d40c-4c9e-84cd-4da11930b213

	column no
		dataType: int64
		formatString: 0
		lineageTag: ee5a046b-bd63-4c27-8aeb-bfbcf05b1dfb
		summarizeBy: none
		sourceColumn: no

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 運用区分_M
		dataType: string
		lineageTag: 7f5a1695-b881-49c8-a7cc-f802d5bc743e
		summarizeBy: none
		sourceColumn: 運用区分_M
		sortByColumn: no

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 【並び替え用】運用区分 = m
		mode: import
		source =
				let
				    ソース = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUXq+ZcrLxu7nU1YoxepEKxkBRZ627nnaPRNJ0Bgo+HLa5Gd9S5EETUCCc+fBRGIB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [no = _t, 運用区分_M = _t]),
				    変更された型 = Table.TransformColumnTypes(ソース,{{"no", Int64.Type}, {"運用区分_M", type text}})
				in
				    変更された型

	annotation PBI_ResultType = Table

